### ISSUE TITLE
Input issue

### ISSUE THREAD

**Issue by takov751** [ewpratten/kobo-rs#10]
Greetings

I have started testing your library on a kobo GLO HD. And for some reason even with the examples built the touchinput does not working at all. I did tested with evtest the event1 is the input that needs to be parsed, but somewhere it's ignores any input. Any idea how i could debug the issue, I am rather new to rust.

**Comment by ewpratten** [comment]
Interesting. I have only ever tested with the original Aura. Are you getting any errors? or just no results

**Comment by takov751** [comment]
No errors, just simply ignores all input. I built simple few line of code just to print out input events from event1 and it works. So i am not sure where to look. Probably i eill try to re create that module to see where is the problem.

Ps.: Thanks for the quick response
