### ISSUE TITLE
GUI disappears when using the touch input; though the binary keeps running

### ISSUE THREAD

**Issue by ivy-rew** [ewpratten/kobo-rs#11]
Hi @ewpratten 

This Rust environment is just what I was looking for in order to experiment on my Kobo. 
Thanks for sharing :handshake: :sunglasses: 

I've compiled all your examples, and ran them on my kobo.
The initial UI is rendered as expected, 
as soon as I try to use the touch input to select a button (e.g. on gui)
the normal Nickel screen appears again, although the gui binary is still running in my terminal, 
where I started it from SSH.

The behaviour is the same on both of my devices: Kobo Libra H20 and Kobo Elipsa 2E with Firmware 4.38.23171

Is that intended? Or am I missing something obvious? 
Any ideas how I can keep the example-gui the main windows which receives touch events?

![overdraw-example](https://github.com/user-attachments/assets/d7d41529-86c3-4e52-a6d3-824335ffea1f)

**Comment by ewpratten** [comment]
Huh, that's kinda weird. I've only ever tried this on an Aura and did not have this problem.

Have you tried killing the nickle process from the terminal? I assume the two are just fighting for the screen at the same time.

**Comment by ivy-rew** [comment]
Thanks for your response, yes the running Nickel seems to be one of the problems.
Killing it manually avoids this overlay issues: so `killall -q -TERM nickel` helps.

**Comment by ewpratten** [comment]
Ah, good find
